**张量（Tensor）** 是一种与数组和矩阵非常相似的专用数据结构。 在PyTorch中，我们使用张量编码模型的输入和输出，以及模型参数。

张量类似于NumPy的ndarray，不同之处在于张量可以在GPU或其他硬件加速器上运行。实际上，张量和NumPy数组通常可以共享相同的底层内存，从而消除复制数据的需求（参见与 NumPy 的桥接）。张量 也为自动微分优化（我们稍后会在Autograd部分详细介绍）。如果你熟悉ndarrays，Tensor API你会非常熟悉。如果没有，就跟着看吧！

In [1]:
import torch
import numpy as np

### PART1. 张量的初始化

张量可以从直接的数据中初始化：

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

也可从numpy数组初始化：（实际上，二者可以相互转换）

In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

基于已有的张量，我们可以创建新的张量：

In [4]:
x_ones = torch.ones_like(x_data) # 这将返回一个与x_data形状相同的张量，并填充1
print(f"填充1的张量: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # 这里生成一个随机填充的张量，dtype可以指定张量的数据类型
print(f"随机填充的张量: \n {x_rand} \n")

填充1的张量: 
 tensor([[1, 1],
        [1, 1]]) 

随机填充的张量: 
 tensor([[0.8669, 0.2689],
        [0.4111, 0.6481]]) 



下方中shape是决定张量维数的元组（行，列）。

In [5]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.2133, 0.9803, 0.9577],
        [0.4074, 0.8203, 0.6144]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


### PART2. 张量的属性

张量的属性包括它们的形状、数据类型以及存储张量的设备等：

In [7]:
tensor = torch.rand(3,4)

print(f"张量形状: {tensor.shape}")
print(f"张量的数据类型: {tensor.dtype}")
print(f"张量存储设备: {tensor.device}")

张量形状: torch.Size([3, 4])
张量的数据类型: torch.float32
张量存储设备: cpu


### PART3. 张量的运算

此处详尽介绍了1200 余种张量运算，涵盖算术运算、线性代数、矩阵操作（转置、索引、切片）、采样等各类操作。

上述全部运算均可在 CPU 以及各类加速硬件上运行，例如 CUDA、MPS、MTIA、XPU。如果你使用Colab环境（谷歌提供的云端 Jupyter Notebook），可以通过「Runtime > Change runtime type > GPU」来启用硬件加速。

张量默认在 CPU 上创建。我们需要先确认加速设备可用，再通过 .to() 方法，把张量显式迁移到加速设备。请记住：在不同设备之间拷贝大张量，会消耗大量时间与显存或内存资源！

In [ ]:
# 如果当前存在可用的加速器，我们就将张量迁移至该加速器上。
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

接下来展示一些对张量的操作（运算）：

**张量索引和切片**    

","用于隔开不同维度，":"表示该维度全部元素，"..."表示剩下所有维度（可用于高维张量）。

In [10]:
tensor = torch.ones(4, 4)
print(f"第一行: {tensor[0]}")
print(f"第一列: {tensor[:, 0]}")
print(f"最后一列: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

第一行: tensor([1., 1., 1., 1.])
第一列: tensor([1., 1., 1., 1.])
最后一列: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**连接张量** 你可以用它在给定维度上串接一列张量。 另见torch.stack， 另一个与 有细微区别的张量连接算符。torch.cattorch.cat

In [11]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])
